export const PAGE_LIST = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  FIND_ID: '/find-id',
  FIND_PASSWORD: '/find-password',
  PROFILE_SETTING: '/setting/profile',
  PROJECT_MANAGEMENT: '/project/management',
  DASTHBOARD: '/dashboard',
  SOCIAL_HOME: '/social/home',
  SOCIAL_SCRAP: '/social/scrap',
  SOCIAL_CREATE: '/social/review/write',
  SOCIAL_FOLLOWER: '/social/follower',
  SOCIAL_PROFILE: '/social/user',
  NOT_FOUND_404: '/404',
};
